apiVersion: v1
kind: Namespace
metadata:
  name: hobby-lobby
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: hobby-lobby
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: hobby-lobby
  namespace: hobby-lobby
spec:
  type: ClusterIP
  selector:
    app: hobby-lobby
  ports:
  - name: server
    protocol: TCP
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hobby-lobby
  namespace: hobby-lobby
  labels:
    app: hobby-lobby
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hobby-lobby
  template:
    metadata:
      labels:
        app: hobby-lobby
    spec:
      containers:
      - name: hobby-lobby
        image: hobby-lobby:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_URL
          value: "postgres.hobby-lobby-db.svc.cluster.local"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: "postgres"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
